### ISSUE TITLE
Will not execute (tried windows 10 and windows 11)

### ISSUE THREAD

**Issue by n0bel** [DazDSP/EasyDRF#6]
C:\Ham\EasyDRF>easydrf
This version of C:\Ham\EasyDRF\EasyDRF.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

Windows 11 22H2 22621.1265

Downloaded from Release folder https://github.com/DazDSP/EasyDRF/blob/master/Release/EasyDRF.exe

Anti-Virus doesn't seem to be an issue (windows defender) nothing about the app is logged there.

Any ideas?

**Comment by DazDSP** [comment]
That error happens when the download is interrupted for some reason (like an AV false positive detection), causing a corrupted file.
All major AVs should now have EasyDRF whitelisted in their latest definitions.
Some web browsers may block unknown apps. Perhaps try another browser to download, or edit security settings for the site.

**Comment by n0bel** [comment]
Re-downloading worked.  It did feel like some sort of corrupted .exe file.  
Interesting that I downloaded it twice just to be sure before creating the Issue.
Thank you!
